security:
  basic:
    enabled: false

  sessions: stateless

spring:
  application:
    name: JavaCombat

  datasource:
    username: wjc
    password: 123456
    url: jdbc:mysql://localhost:3306/jcombat?useUnicode=true
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      test-while-idle: true
      time-between-eviction-runs-millis: 3600000
      validation-query: SELECT 1

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true